### PR TITLE
Addressed code review comments

### PR DESCRIPTION
**Pull request by darrensiegel**
Addressed code review comments

### CODE REVIEW

**Review by jsewall — CHANGES_REQUESTED** [review]
This code doesn't compile with the create_problem_dict definition as is. I took out the @staticmethod annotation and moved the function definition to precede the call. That seems to work ok. It may be enough to just remove @staticmethod

**Comment by darrensiegel** [comment]
I tried and failed to set up my environment to be able to compile this code. I'm not a python developer, but googling suggested that "python setup.py install"  would install dependencies en route to allowing me to compile/run. But this eventually fails due to c compile ("cc") missing.  The Xcode command line tools installation to install cc simply hangs.  

So, I've made the changes that you mentioned that worked for you: removing the static method annotation and moving the method definition above where it is called.

**Comment by jsewall** [comment]
These changes appear to work fine. Many thanks,

**Comment by Ringenberg** [comment]
Here is a link to the XBlock SDK that is very useful for development and testing: https://github.com/edx/xblock-sdk

**Pull request merged**
